BibliotecaCUNOR/Models/Prestamo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BibliotecaCUNOR.Models
{
    public partial class Prestamo
    {
        public Prestamo()
        {
            DetPrestamo = new HashSet<DetPrestamo>();
        }

        public int CodPrestamo { get; set; }
        public DateTime FechaPrestamo { get; set; }

        //   [DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}", ApplyFormatInEditMode =true)]
        public DateTime FechaDevolucion { get; set; }
        public DateTime FechaRecepcion { get; set; }
        public int? Mora { get; set; }
        public string Tipo { get; set; }

        public int CodUsuario { get; set; }

        [NotMapped]
        public int DiasAtraso { get; set; }

        [NotMapped]
        public List<int> Libros { get; set; }


        public virtual Usuario CodUsuarioNavigation { get; set; }
        public virtual ICollection<DetPrestamo> DetPrestamo { get; set; }
    }
}

BibliotecaCUNOR/Controllers/PrestamoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BibliotecaCUNOR.Models;
using System.Linq.Dynamic;
using System.Linq.Dynamic.Core;
using System.Security.Principal;
using Rotativa.AspNetCore;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNetCore.Authorization;

namespace BibliotecaCUNOR.Controllers
{
    [Authorize(Roles ="Bibliotecario")]
    public class PrestamoController : Controller
    {
        //Atributos para el JSON
        public string draw = "";
        public string start = "";
        public string length = "";
        public string sortColumn = "";
        public string sortColumnDir = "";
        public string searchValue = "";
        public int pageSize, skip, recordsTotal;
        private readonly bd_bibliotecaContext _context;

        public PrestamoController(bd_bibliotecaContext context)
        {
            _context = context;
        }



        // GET: Prestamo
        public async Task<IActionResult> Index()
        {

            return RedirectToAction("Ficha");
        }

        // GET: Prestamo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prestamo = await _context.Prestamo
                .Include(p => p.CodUsuarioNavigation)
                .FirstOrDefaultAsync(m => m.CodPrestamo == id);
            if (prestamo == null)
            {
                return NotFound();
            }

            return View(prestamo);
        }


        //Buscar Usuario
        [AcceptVerbs("GET","POST")]
        public JsonResult ObtenerInformacion(int idUsuario)
        {
            List<Usuario> lst;
            
                lst = (from d in _context.Usuario
                       where d.CodUsuario==idUsuario
                       select d).ToList();
                return Json(lst);
           
        }

        [AcceptVerbs("GET", "POST")]
        public JsonResult ObtenerInformacionLibro(int[] idLibro)
        {
            
            foreach (var i in idLibro)
            {
                List<Libro> lst;
                lst = (from d in _context.Libro
                       where d.CodLibro == i
                       select d).ToList();
                return Json(lst);
            }
            return Json(true);

        }


        // GET: Prestamo/Create
        public IActionResult Create()
        {
           
            ViewData["CodUsuario"] = new SelectList(_context.Usuario, "CodUsuario", "FullName");
            ViewData["CodLibro"] = new SelectList(_context.Libro, "CodLibro", "Titulo");
            return View();
        }

        // POST: Prestamo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CodPrestamo,FechaPrestamo,FechaDevolucion,FechaRecepcion,Mora,Tipo,CodUsuario,Libros")] Prestamo prestamo)
        {
            if (ModelState.IsValid)
            {
                bd_bibliotecaContext context2 = new bd_bibliotecaContext();
                foreach (var i in prestamo.Libros)
                {
                    var libro = context2.Libro.Where(w => w.CodLibro == i).FirstOrDefault();
                    if (libro != null)
                    {
                        if (libro.Ejemplares==0 && libro.Estado.Equals("Ocupado"))
                        {
                            //Hacer aca la validacion del modal 
                            TempData["mensajePresE"] = "Creado!";
                            return RedirectToAction("Ficha");
                        }
                        else if(libro.Ejemplares == 0 && libro.Estado.Equals("Perdido"))
                        {
                            //Hacer aca la validacion del modal 
                            TempData["mensajePresE"] = "Error";
                            return RedirectToAction("Ficha");
                        }
                        if (libro.Ejemplares != 0)
                        {
                            prestamo.DetPrestamo.Add(new DetPrestamo { CodLibro = i, Estado = "Ocupado" });
                            libro.Ejemplares = libro.Ejemplares - 1;
                            await context2.SaveChangesAsync();
                        }
                        else if (libro.Ejemplares == 0 && libro.Estado.Equals("Disponible"))
                        {
                            prestamo.DetPrestamo.Add(new DetPrestamo { CodLibro = i, Estado = "Ocupado" });
                            libro.Estado = "Ocupado";
                            await context2.SaveChangesAsync();
                        }
                       

                    }

                    
                }
                // _context.Libro.Update(new Libro {Estado="Dipsonible" });
                DateTime thisDay = DateTime.Today;
                prestamo.FechaPrestamo = thisDay;
                _context.Add(prestamo);
                await _context.SaveChangesAsync();


                return RedirectToAction("ConfirmacionFicha", new { id = prestamo.CodPrestamo });


                /*
                var trabajoGraduacion = await _context.TrabajoGraduacion
                .Include(t => t.CodAsesorNavigation)
                .Include(t => t.CodCarreraNavigation)
                .Include(t => t.CodCatNavigation)
                .Include(t => t.CodTipotrabajoNavigation)
                .Include(t => t.TrabajoPalabraClave)
                .ThenInclude(e => e.CodPalabraClaveNavigation)
                .FirstOrDefaultAsync(m => m.CodRegistro == id);
                */

                //return RedirectToAction(nameof(Index));
            }
            ViewData["CodUsuario"] = new SelectList(_context.Usuario, "CodUsuario", "Apellido", prestamo.CodUsuario);
            return View(prestamo);
        }

        /*
        // GET: Prestamo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prestamo = await _context.Prestamo.FindAsync(id);
            if (prestamo == null)
            {
                return NotFound();
            }
            ViewData["CodUsuario"] = new SelectList(_context.Usuario, "CodUsuario", "Apellido", prestamo.CodUsuario);
            return View(prestamo);
        }

        // POST: Prestamo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CodPrestamo,FechaPrestamo,FechaDevolucion,FechaRecepcion,Mora,Tipo,CodUsuario")] Prestamo prestamo)
        {
            if (id != prestamo.CodPrestamo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(prestamo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PrestamoExists(prestamo.CodPrestamo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CodUsuario"] = new SelectList(_context.Usuario, "CodUsuario", "Apellido", prestamo.CodUsuario);
            return View(prestamo);
        }

        // GET: Prestamo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prestamo = await _context.Prestamo
                .Include(p => p.CodUsuarioNavigation)
                .FirstOrDefaultAsync(m => m.CodPrestamo == id);
            if (prestamo == null)
            {
                return NotFound();
            }

            return View(prestamo);
        }

        // POST: Prestamo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var prestamo = await _context.Prestamo.FindAsync(id);
            _context.Prestamo.Remove(prestamo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PrestamoExists(int id)
        {
            return _context.Prestamo.Any(e => e.CodPrestamo == id);
        }

        */


        [AcceptVerbs("GET", "POST")]
        public JsonResult ObtenerInformacion1()
        {
            List<ViewModel> lst;

            lst = (from e in _context.DetPrestamo
                   join d in _context.Libro on e.CodLibro equals d.CodLibro
                   join i in _context.Prestamo on e.CodPrestamo equals i.CodPrestamo
                   join h in _context.Usuario on d.CodUsuario equals h.CodUsuario
                   select new ViewModel
                   {
                       Libro = d.Titulo,
                       NombreUsuario = h.FullName,
                       Tipo = i.Tipo,
                       FechaSolicitud = i.FechaPrestamo,
                       FechaRecepcion = i.FechaRecepcion,

                   }).ToList();
            return Json(lst);

        }


        //PRESTAMO ESTUDIANTE
        [HttpGet]
        public IActionResult Ficha()

BibliotecaCUNOR/Views/Prestamo/Boleta.cshtml
@model BibliotecaCUNOR.Models.Prestamo
@{
    ViewData["Title"] = "Boleta";
    Layout = null;
}
<head>
    <style>
        #fecha {
            color: red;
        }

        .greeting h2 {
            margin: 0px;
            line-height: 25px;
        }

        .greeting h3 {
            margin: 0px;
            line-height: 25px;
        }

        .greeting h4 {
            margin: 0px;
            line-height: 25px;
        }

        #content {
            position: relative;
        }

            #content img {
                position: absolute;
                top: 0px;
                right: 0px;
            }

        .ribbon {
            position: relative;
            top: -16px;
            right: -706px;
            height: 80px;
            width: 80px;
        }

        table {
            width: 100%;
            border: 1px solid black;
        }

        table, th, td {
            border-collapse: collapse;
        }

        th, td {
            padding: 1px;
            text-align: left;
        }

        #t01 tr:nth-child(even) {
            background-color: #eee;
        }

        #t01 tr:nth-child(odd) {
            background-color: #fff;
        }

        #t01 th {
            background-color: lightgrey;
        }
    </style>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link href="~/css/boleta.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
</head>

<body style="background-color:white">
    <div id="content">
        <img src="~/imagenes/logo-usac.png" class="ribbon" />
    </div>
    <div class="greeting">
        <center>
            <h2>UNIVERSIDAD DE SAN CARLOS DE GUATEMALA</h2>
            <h3>CENTRO UNIVERSITARIO DEL NORTE -CUNOR-</h3>
            <h4>BOLETA DE PRESTAMO - BIBLIOTECA CUNOR</h4>
        </center>
    </div>
    <table style="border:hidden">
        <tr>
            <td><strong>Lector:&nbsp;&nbsp; </strong>@Model.CodUsuarioNavigation.Nombre @Model.CodUsuarioNavigation.Apellido</td>&nbsp;&nbsp;
            <td><strong>Rol:&nbsp;&nbsp; </strong>@Model.CodUsuarioNavigation.CodRolusuarioNavigation.Rol</td>
        </tr>
    </table>
    <br />
    <div class="greeting">
        <h3 id="1">Libros Prestados</h3>
    </div>

    @{ int contador = 1;}
    <table id="t01">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Titulo</th>
                <th scope="col">Clave del Libro</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.DetPrestamo)
            {
                <tr>
                    <th scope="row">@contador</th>
                    <td>@item.CodLibroNavigation.Titulo</td>
                    <td>@item.CodLibroNavigation.Clave</td>
                </tr>
                contador = contador + 1;
            }
        </tbody>
    </table>
    <br />
    <table style="border:hidden">
        <tr>
            <td><strong>Fecha Prestamo:&nbsp;&nbsp; </strong>@Model.FechaPrestamo</td>
            <td><strong>Fecha Devolucion:&nbsp;&nbsp; </strong>@Model.FechaDevolucion</td>
            <td><strong>Tipo de Prestamo:&nbsp;&nbsp; </strong>@Model.Tipo</td>
        </tr>
    </table>
    <hr />
    <p style="text-align:justify">
        El libro/libros que estoy solicitando a la Biblioteca del CUNOR se encuentra en buen estado, las fechas de préstamo y de entrega se encuentran indicadas en la parte superior, 
        yo <strong>@Model.CodUsuarioNavigation.Nombre @Model.CodUsuarioNavigation.Apellido</strong>
        me comprometo  a cumplirlas y evitar las sanciones correspondientes. En caso de maltrato o extravió del libro/libros aquí mencionado tendré que cubrir la totalidad del costo para que sea repuesto.
        Costo por día de retraso Q 2.00
    </p>
    <center>
        <p>_______________________________________________</p>
        <p> Firma de Lector @Model.CodUsuarioNavigation.Nombre @Model.CodUsuarioNavigation.Apellido </p>
        <p align="right">Boleta Generada el: <strong id="fechayhora"></strong></p>
    </center>



</body>

<script>
    showTime();
    function showTime() {
        myDate = new Date();
        days = myDate.getDate();
        month = myDate.getMonth()+1;
        hours = myDate.getHours();
        minutes = myDate.getMinutes();
        seconds = myDate.getSeconds();
        if (days < 10) days = "0" + days;
        if (hours < 10) hours = 0 + hours;
        if (hours < 10) month = "0" + hours;
        if (minutes < 10) minutes = "0" + minutes;
        if (seconds < 10) seconds = "0" + seconds;

        $("#fechayhora").text(days + "/" + month + "/" + myDate.getFullYear() + " " + hours + ":" + minutes + ":" + seconds);
        setTimeout("showTime()", 1000);
    }
</script>

BibliotecaCUNOR/Views/Prestamo/Confirmacion.cshtml
@{
    ViewData["Title"] = "Confirmacion";
}

@model BibliotecaCUNOR.Models.Prestamo

<!DOCTYPE html>
<html lang="es">
<head>
    <title>Prestamos</title>
    <!--DATEPICKER-->
    <link rel="stylesheet" type="text/css" href="~/calendario/jquery-ui-1.12.1.custom/jquery-ui.css" />
    <script src="~/calendario/jquery-ui-1.12.1.custom/jquery-ui.js"></script>

    <!--Son referencias que agregamos-->
    <!--Tabla de usuarios y libros
        <script src="~/lib/jquery/dist/jquery-ui.min.js" type="text/javascript"></script>
        <script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
    -->
    <!--CHOSEN-->
    <script src="~/chosen/chosen.jquery.js" type="text/javascript"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="~/chosen/chosen.css" />
</head>
<body>
    <div class="container">
        <div class="page-header">
            <h1 class="all-tittles">Sistema bibliotecario <small>Préstamos</small></h1>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 lead">
                <ol class="breadcrumb">
                    <li><a href="~/Prestamo/Ficha">Nuevo Prestamo</a></li>
                    <li class="active">Confirmacion</li>
                </ol>
            </div>
        </div>
    </div>

    <!--ESTO SE QUEDA-->
    <div class="container-fluid">
        <div class="col-xs-12">
            <div class="title-flat-form1 title-flat-blue">Confirmacion</div>
            <div class="panel-body">
                <table class="table-active">
                    <tr>
                        <th colspan="2">Prestamo de Libros</th>
                    </tr>
                    <tr>
                        <th>Referencia</th>
                        <td>&nbsp;&nbsp;12</td>
                    </tr>
                    <tr>
                        <th>Fecha del Prestamo</th>
                        <td>&nbsp;&nbsp;23/25/23</td>
                    </tr>
                </table>
            </div>
            <hr />
            <form class="form-padding1">
                <div class="panel  panel-footer" style="padding-left:15%; padding-right:15%;">
                    <div class="panel-heading"></div>
                    <table class="table">
                        <thead>
                            <tr>
                                <td colspan="2" style="text-align:center">El prestamo ha sido aplicado exitosamente</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>Categoria</th>
                                <td>En casa</td>
                            </tr>
                            <tr>
                                <th>Empresa</th>
                                <td>CUNOR</td>
                            </tr>
                            <tr>
                                <th>Nis</th>
                                <td>23458</td>
                            </tr>
                            <tr>
                                <th>Nombre</th>
                                <td>Emanuel Amperez</td>
                            </tr>
                            <tr>
                                <th>Monto a Pagar</th>
                                <td>250</td>
                            </tr>
                            <tr>
                                <th>Libros Prestados</th>
                                <td>
                                    <ul class="list-group">
                                        <li>Jola</li>
                                        <li>Hola</li>
                                        <li>Pepo</li>
                                    </ul>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <hr />
                    <center>
                        <label><strong>Carnet</strong>201741942 - Emanuel Marlon Fabricio Amperez Tahuico</label>
                    </center>
                    <p style="text-align:center">
                        Nota: Este documento es un comprobante electronico del prestamo de Libros prestados.
                        Los libros anterior mencionados quedan a responsabilidad del estudiante que los ha solicitado
                    </p>
                </div>
                <div class="col-xs-12">
                    <p class="text-center">
                        <button type="reset" class="btn btn-info" style="margin-right: 20px;"><i class="zmdi zmdi-roller"></i> &nbsp;&nbsp; Limpiar</button>
                        <button type="submit" class="btn btn-primary"><i class="zmdi zmdi-floppy"></i> &nbsp;&nbsp; Guardar</button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</body>

</html>

BibliotecaCUNOR/Views/Prestamo/DevolucionPrestamo.cshtml
@model BibliotecaCUNOR.Models.Prestamo

@{
    ViewData["Title"] = "UsuarioDetalle";
    Layout = null;
}


<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Detalle del Prestamo </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" asp-controller="Prestamo" asp-action="DevolverLibro">
                <div class="modal-body">
                    <ol class="breadcrumb">
                        <li><a href="#" class="close" data-dismiss="modal">Devolucion de Libros</a></li>
                        <li class="active">Devolucion del Usuario : <strong>@(Model.CodUsuarioNavigation.Nombre + " " + @Model.CodUsuarioNavigation.Apellido)</strong></li>
                    </ol>

                    <div class="panel panel-default">
                        <div class="panel-heading">Datos del Usuario</div>
                        <div class="panel-body">
                            <dl class="dl-horizontal">
                                <dt>Tipo de Prestamo</dt>
                                <dd>@Model.Tipo</dd>
                                <dt>Fecha de Prestamo</dt>
                                <dd>@Model.FechaPrestamo</dd>
                                <dt>Fecha Devolucion</dt>
                                <dd>@Model.FechaDevolucion</dd>
                                <dt>Dias de Atraso</dt>
                                <dd>@Model.DiasAtraso</dd>
                                <dt>Mora Generada</dt>
                                <dd>@Model.Mora</dd>
                            </dl>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">Datos del Usuario</div>
                        <div class="panel-body">
                            <dl class="dl-horizontal">
                                <dt>Nombre</dt>
                                <dd>@Model.CodUsuarioNavigation.Nombre</dd>
                                <dt>Carnet</dt>
                                <dd>@Model.CodUsuarioNavigation.Usuario1</dd>
                            </dl>
                        </div>
                    </div>

                    @{int contador = 0; }
                    @{string conca = "libro"; }
                    @{string idlibro = "idlibro"; }
                    <div class="panel panel-default">
                        <div class="panel-heading">Libro/Libros Prestados</div>
                        <div class="panel-body">
                            <ul class="list-group">
                                @foreach (var item in Model.DetPrestamo)
                                {
                                    <li class="list-group-item">
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="customSwitch1" name="@conca" value="@Html.DisplayFor(modelItem =>item.CodLibro)">
                                            <input type="hidden" name="@idlibro" value="@Html.DisplayFor(modelItem =>item.CodLibro)" />
                                            <label class="custom-control-label" for="customSwitch1">@Html.DisplayFor(modelItem => item.CodLibroNavigation.Titulo)</label>
                                        </div>
                                    </li>
                                    contador = contador + 1;
                                    conca = conca + "" + contador;
                                    idlibro = idlibro + "" + contador;
                                }
                            </ul>
                            <input type="hidden" name="mora" value="@Model.Mora" />
                            <input type="hidden" name="codPrestamo" value="@Model.CodPrestamo" />
                        </div>
                    </div>
                    <center>
                        <input type="submit" value="Devolver Prestamo" />
                    </center>
                </div>
            </form>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>

            </div>
        </div>

    </div>
</div>
<script>
    $('.checkbox').prop('indeterminate', true)
</script>

BibliotecaCUNOR/Views/Prestamo/DevolverLibro.cshtml
@model BibliotecaCUNOR.Models.Prestamo

<!DOCTYPE html>
<html lang="es">
<head>
    <title>Detalle Prestamo</title>

</head>
<body>
    <div class="container">
        <div class="page-header">
            <h1 class="all-tittles">Sistema bibliotecario <small>Préstamos</small></h1>
        </div>
    </div>

    <div class="container-fluid" style="margin: 50px 0;">
        <div class="row">
            <div class="col-xs-12 col-sm-4 col-md-3">
                <img src="~/assets/img/user01.png" alt="user" class="img-responsive center-box" style="max-width: 110px;">
            </div>
            <div class="col-xs-12 col-sm-8 col-md-8 text-justify lead">
                Detalles del Prestamo Devuelto
            </div>
        </div>
    </div>

    @{int contador = 0; }
    <!--ESTO SE QUEDA-->
<div class="container-fluid">
    <div class="container-flat-form">
        <div class="title-flat-form title-flat-blue">Generar una nueva boleta de Prestamo</div>
        <form class="form-padding1">
            <div class="panel panel-footer" style="padding-left:15%; padding-right:15%">
                <div class="panel-heading">Datos del Usuario</div>
                <div class="panel-body">
                    <dl class="dl-horizontal">
                        <dt>Datos del Usuario</dt>
                        <dd>@Model.CodUsuarioNavigation.Nombre @Model.CodUsuarioNavigation.Apellido</dd>
                        <dt>Telefono</dt>
                        <dd>@Model.CodUsuarioNavigation.Telefono</dd>
                        <dt>Carnet</dt>
                        <dd>@Model.CodUsuarioNavigation.Usuario1</dd>
                        <dt>Correo Electronico</dt>
                        <dd>@Model.CodUsuarioNavigation.CorreoElectronico</dd>
                    </dl>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Informacion del Prestamo</div>
                <div class="panel-body">
                    <dl class="dl-horizontal">
                        <dt>Fecha de Prestamo</dt>
                        <dd>@Model.FechaPrestamo</dd>
                        <dt>Fecha Devolucion</dt>
                        <dd>@Model.FechaDevolucion</dd>
                        <dt>Dias de Atraso</dt>
                        <dd>@Model.DiasAtraso</dd>
                        <dt>Mora Generado</dt>
                        <dd>Q.@Model.Mora.00</dd>
                    </dl>
                </div>
            </div>

            <div class="panel panel-footer" style="padding-left:15%; padding-right:15%">
                <div class="panel-heading">Libro/Libros Prestados</div>
                <div class="panel-body">
                    <ul class="list-group">
                        @foreach (var item in Model.DetPrestamo)
                        {
                            if (item.Estado.Equals("Perdido"))
                            {
                                <li class="list-group-item" style="background:red">
                                    @Html.DisplayFor(modelItem => item.CodLibroNavigation.Titulo)
                                </li>
                                contador = contador + 1;
                            }
                            else
                            {
                                <li class="list-group-item">
                                    @Html.DisplayFor(modelItem => item.CodLibroNavigation.Titulo)
                                </li>
                            }

                        }
                    </ul>
                    <input type="hidden" name="CodPrestamo" value="@Model.CodPrestamo" />
                </div>
                @if (contador > 0)
                {
                    <hr />
                    <center>
                        <label><strong>Carnet&nbsp;&nbsp;</strong>@Model.CodUsuarioNavigation.Usuario1&nbsp; - &nbsp;@Model.CodUsuarioNavigation.Apellido @Model.CodUsuarioNavigation.Nombre</label>
                    </center>
                    <p style="text-align:center">
                        Nota: A consecuencia de que el estudiante ha perdido los libros que estan enmarcados en color rojo,
                        puede generar el respectivo <strong>Reporte</strong> de <strong>perdida de libros</strong>, en las opciones
                        <strong>Generar Informe</strong> y <strong>Guardar Informe</strong>.
                    </p>
                }
            </div>

        </form>
    </div>


    <center>
        <div class="col-xs-12">
            @if (contador > 0)
            {
                <form asp-action="ImprimirReporte">
                    <button type="submit" formtarget="_blank" class="btn-primary"><i class="zmdi zmdi-print"></i> &nbsp;&nbsp;Imprimi Informe</button>
                    <input name="CodigoPrestamo" type="hidden" value="@Model.CodPrestamo" />
                </form>
                <br />
                <form asp-action="DescargarReporte">
                    <button type="submit" class="btn-success"><i class="zmdi zmdi-floppy"></i> &nbsp;&nbsp;Guardar Informe</button>
                    <input name="CodigoPrestamo" type="hidden" value="@Model.CodPrestamo" />
                </form>
            }
            <br />
            <form>
                <button asp-action="Ficha" asp-controller="Prestamo" type="submit" class="btn-primary">Prestamos</button>
            </form>
        </div>
    </center>
</div>
</body>

</html>